/**
 * Resolves an icon *name* (stored in the app catalogue / settings) to a
 * Lucide component. Curated map keeps tree-shaking effective - importing the
 * whole icon pack would add several megabytes to the bundle.
 */

import {
  Activity,
  AlertTriangle,
  AppWindow,
  AudioLines,
  Braces,
  Calculator,
  Calendar,
  CheckCircle2,
  ChevronLeft,
  ChevronRight,
  Chrome,
  Clapperboard,
  Clock,
  Cpu,
  Database,
  Disc3,
  FileText,
  Film,
  FolderOpen,
  Gamepad2,
  Globe,
  HardDrive,
  Headphones,
  Info,
  Layers,
  Lock,
  Mail,
  MemoryStick,
  MessageCircle,
  MessageSquare,
  Microchip,
  Monitor,
  MonitorPlay,
  Moon,
  Music,
  NotebookText,
  PenTool,
  Power,
  RefreshCw,
  RotateCw,
  Rocket,
  Send,
  Server,
  Settings2,
  Sparkles,
  SquareTerminal,
  Star,
  Thermometer,
  Users,
  Video,
  Wifi,
  Youtube,
  Zap,
  type LucideIcon,
} from 'lucide-react'

const ICONS: Record<string, LucideIcon> = {
  Activity,
  AlertTriangle,
  AppWindow,
  AudioLines,
  Braces,
  Calculator,
  Calendar,
  CheckCircle2,
  ChevronLeft,
  ChevronRight,
  Chrome,
  Clapperboard,
  Clock,
  Cpu,
  Database,
  Disc3,
  FileText,
  Film,
  FolderOpen,
  Gamepad2,
  Globe,
  HardDrive,
  Headphones,
  Info,
  Layers,
  Lock,
  Mail,
  MemoryStick,
  MessageCircle,
  MessageSquare,
  Microchip,
  Monitor,
  MonitorPlay,
  Moon,
  Music,
  NotebookText,
  PenTool,
  Power,
  RefreshCw,
  RotateCw,
  Rocket,
  Send,
  Server,
  Settings2,
  Sparkles,
  SquareTerminal,
  Star,
  Thermometer,
  Users,
  Video,
  Wifi,
  Youtube,
  Zap,
}

export const AVAILABLE_ICONS = Object.keys(ICONS)

interface AppIconProps {
  name: string
  className?: string
  strokeWidth?: number
}

export function AppIcon({ name, className, strokeWidth = 1.75 }: AppIconProps) {
  const Component = ICONS[name] ?? AppWindow
  return <Component className={className} strokeWidth={strokeWidth} aria-hidden="true" />
}
